### ISSUE TITLE
module view -- break down vle use by item ⚖104

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/data-explorer#101] opened 2017-05-30 08:55 UTC
Really useful being able to click on items within VLE content to view which students have consumed

**Comment by robbristow-jisc** [comment] 2017-08-04 08:31
Is this the same as 104?

**Comment by leebaylis** [comment] 2017-08-04 08:55
oh -- maybe what I wrote for 100 was for this instead!
OK, I am confused now -- I thought one of these was for click on a student and see what they have consumed, and the other one was for click the content and see which students have consumed it.

**Comment by leebaylis** [comment] 2017-08-04 09:20
duplicate of #100

**Closed by leebaylis** 2017-08-04 09:20 UTC
Labels: accepted @ high priority, feature, please test, released on staging
